
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import *
import Database
class Ui_MainWindow3(object):
    def setupUi(self, MainWindow,cardno):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 689)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("foo.jpg")))
        MainWindow.setPalette(palette)
        self.cardno=cardno
        MainWindow.setWindowIcon(QIcon('coffee.jpg'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 320, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 230, 91, 16))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(130, 260, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 110, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 290, 71, 16))
        self.label_17.setObjectName("label_17")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(130, 530, 47, 13))
        self.label_32.setObjectName("label_32")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 140, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(130, 500, 47, 16))
        self.label_30.setObjectName("label_30")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(130, 440, 47, 13))
        self.label_26.setObjectName("label_26")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(130, 200, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(20, 470, 81, 16))
        self.label_27.setObjectName("label_27")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(130, 230, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(130, 170, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(20, 380, 71, 20))
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(130, 470, 47, 13))
        self.label_28.setObjectName("label_28")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.label_15.setObjectName("label_15")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(130, 410, 47, 13))
        self.label_24.setObjectName("label_24")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(130, 380, 47, 13))
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(20, 440, 101, 16))
        self.label_25.setObjectName("label_25")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 500, 101, 16))
        self.label_29.setObjectName("label_29")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(130, 320, 47, 13))
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(20, 410, 91, 16))
        self.label_23.setObjectName("label_23")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(20, 530, 61, 16))
        self.label_31.setObjectName("label_31")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(130, 290, 47, 13))
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.label.setObjectName("label")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(20, 0, 171, 41))
        self.label_71.setObjectName("label_71")
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(20, 340, 141, 31))
        self.label_74.setObjectName("label_74")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(20, 590, 101, 16))
        self.label_35.setObjectName("label_35")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(190, 200, 141, 16))
        self.label_49.setObjectName("label_49")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(340, 320, 47, 13))
        self.label_58.setObjectName("label_58")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(130, 620, 47, 13))
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(340, 50, 47, 13))
        self.label_40.setObjectName("label_40")
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(340, 440, 47, 13))
        self.label_68.setObjectName("label_68")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(190, 320, 141, 16))
        self.label_57.setObjectName("label_57")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(340, 110, 47, 13))
        self.label_44.setObjectName("label_44")
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(340, 410, 47, 13))
        self.label_64.setObjectName("label_64")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(340, 350, 47, 13))
        self.label_60.setObjectName("label_60")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(130, 590, 47, 13))
        self.label_36.setObjectName("label_36")
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(190, 440, 131, 16))
        self.label_65.setObjectName("label_65")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(340, 290, 47, 13))
        self.label_56.setObjectName("label_56")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(130, 560, 47, 13))
        self.label_34.setObjectName("label_34")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(20, 560, 101, 16))
        self.label_33.setObjectName("label_33")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(190, 380, 121, 16))
        self.label_61.setObjectName("label_61")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(190, 290, 141, 16))
        self.label_55.setObjectName("label_55")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(340, 80, 47, 13))
        self.label_42.setObjectName("label_42")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(340, 230, 47, 13))
        self.label_52.setObjectName("label_52")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(190, 350, 131, 16))
        self.label_59.setObjectName("label_59")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(190, 260, 111, 16))
        self.label_53.setObjectName("label_53")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(190, 80, 101, 16))
        self.label_41.setObjectName("label_41")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(190, 410, 131, 16))
        self.label_63.setObjectName("label_63")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(190, 130, 141, 31))
        self.label_46.setObjectName("label_46")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(340, 380, 47, 13))
        self.label_62.setObjectName("label_62")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(190, 170, 111, 16))
        self.label_47.setObjectName("label_47")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(190, 230, 131, 16))
        self.label_51.setObjectName("label_51")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(20, 620, 111, 16))
        self.label_37.setObjectName("label_37")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(190, 110, 111, 16))
        self.label_43.setObjectName("label_43")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(340, 200, 47, 13))
        self.label_50.setObjectName("label_50")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(340, 170, 47, 13))
        self.label_48.setObjectName("label_48")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(340, 260, 47, 13))
        self.label_54.setObjectName("label_54")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(190, 50, 91, 16))
        self.label_39.setObjectName("label_39")
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(190, 560, 131, 16))
        self.label_66.setObjectName("label_66")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(190, 500, 121, 16))
        self.label_69.setObjectName("label_69")
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(190, 530, 131, 16))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(340, 560, 47, 13))
        self.label_73.setObjectName("label_73")
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(190, 470, 131, 16))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(340, 470, 47, 13))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(340, 500, 47, 13))
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(340, 530, 47, 13))
        self.label_78.setObjectName("label_78")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(780, 50, 521, 471))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(810, 580, 221, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1050, 580, 221, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(990, 0, 111, 61))
        self.label_45.setObjectName("label_45")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(1120, 520, 171, 41))
        self.label_79.setObjectName("label_79")
        self.item = QtWidgets.QLineEdit(self.centralwidget)
        self.item.setGeometry(QtCore.QRect(550, 130, 141, 31))
        self.item.setObjectName("item")
        self.quantity = QtWidgets.QLineEdit(self.centralwidget)
        self.quantity.setGeometry(QtCore.QRect(550, 189, 61, 31))
        self.quantity.setObjectName("quantity")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(550, 250, 75, 23))
        self.add.setObjectName("add")
        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setGeometry(QtCore.QRect(640, 250, 75, 23))
        self.remove.setObjectName("remove")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(430, 120, 91, 41))
        self.label_67.setObjectName("label_67")
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(430, 180, 91, 51))
        self.label_70.setObjectName("label_70")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.order = Database.order()
        self.add.clicked.connect(self.add_item)
        self.remove.clicked.connect(self.remove_item)
        self.pushButton_9.clicked.connect(self.ok)
        self.pushButton_10.clicked.connect(self.print_bill)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RS.40"))
        self.label_18.setText(_translate("MainWindow", "GINGER TEA"))
        self.label_4.setText(_translate("MainWindow", "RS.40"))
        self.label_13.setText(_translate("MainWindow", "HOT CHOCOLATE"))
        self.label_16.setText(_translate("MainWindow", "RS.30"))
        self.label_5.setText(_translate("MainWindow", "CAFE LATTE"))
        self.label_6.setText(_translate("MainWindow", "RS.40"))
        self.label_9.setText(_translate("MainWindow", "IRISH CAPPUCINNO"))
        self.label_11.setText(_translate("MainWindow", "IRISH COFFEE"))
        self.label_7.setText(_translate("MainWindow", "CAPPUCINNO"))
        self.label_17.setText(_translate("MainWindow", "ASSAM TEA"))
        self.label_32.setText(_translate("MainWindow", "RS.50"))
        self.label_8.setText(_translate("MainWindow", "RS.40"))
        self.label_30.setText(_translate("MainWindow", "RS.50"))
        self.label_26.setText(_translate("MainWindow", "RS.50"))
        self.label_12.setText(_translate("MainWindow", "RS.50"))
        self.label_27.setText(_translate("MainWindow", "FIRST CRUSH"))
        self.label_14.setText(_translate("MainWindow", "RS.40"))
        self.label_10.setText(_translate("MainWindow", "RS.50"))
        self.label_21.setText(_translate("MainWindow", "CAFE FRAPPE"))
        self.label_28.setText(_translate("MainWindow", "RS.50"))
        self.label_15.setText(_translate("MainWindow", "MASALA TEA"))
        self.label_24.setText(_translate("MainWindow", "RS.60"))
        self.label_22.setText(_translate("MainWindow", "RS.50"))
        self.label_25.setText(_translate("MainWindow", "SHAKEN ESPRESSO"))
        self.label_3.setText(_translate("MainWindow", "CAFE MOCHA"))
        self.label_29.setText(_translate("MainWindow", "GREEN APPLE SODA"))
        self.label_20.setText(_translate("MainWindow", "RS.30"))
        self.label_23.setText(_translate("MainWindow", "CHOCO FRAPPE"))
        self.label_31.setText(_translate("MainWindow", "COOL BLUE"))
        self.label_19.setText(_translate("MainWindow", "RS.30"))
        self.label.setText(_translate("MainWindow", "ESPRESSO"))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#b30000;\">HOT</span></p></body></html>"))
        self.label_74.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#aa0000;\">COLD</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "LEMON ICED TEA"))
        self.label_49.setText(_translate("MainWindow", "PANNER TIKKA SANDWICH"))
        self.label_58.setText(_translate("MainWindow", "RS.60"))
        self.label_38.setText(_translate("MainWindow", "RS.50"))
        self.label_40.setText(_translate("MainWindow", "RS.50"))
        self.label_68.setText(_translate("MainWindow", "RS.40"))
        self.label_57.setText(_translate("MainWindow", "CHICKEN TIKKA SANDWICH"))
        self.label_44.setText(_translate("MainWindow", "RS.50"))
        self.label_64.setText(_translate("MainWindow", "RS.50"))
        self.label_60.setText(_translate("MainWindow", "RS.60"))
        self.label_36.setText(_translate("MainWindow", "RS.50"))
        self.label_65.setText(_translate("MainWindow", "NUTTY BROWNIE"))
        self.label_56.setText(_translate("MainWindow", "RS.35"))
        self.label_34.setText(_translate("MainWindow", "RS.50"))
        self.label_33.setText(_translate("MainWindow", "MASALA LEMONATE"))
        self.label_61.setText(_translate("MainWindow", "CHICKEN PANINI"))
        self.label_55.setText(_translate("MainWindow", "PANNER SPICY CHATAKA"))
        self.label_42.setText(_translate("MainWindow", "RS.50"))
        self.label_52.setText(_translate("MainWindow", "RS.55"))
        self.label_59.setText(_translate("MainWindow", "CHICKEN BURGER"))
        self.label_53.setText(_translate("MainWindow", "VEG BURGER"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>COLD CHOCOLATE</p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "CHOCOLATE FANTASY"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#aa0000;\">BIG EATS</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "RS.60"))
        self.label_47.setText(_translate("MainWindow", "CORN SANDWICH"))
        self.label_51.setText(_translate("MainWindow", "VEG PANINI"))
        self.label_37.setText(_translate("MainWindow", "PEACH ICED TEA"))
        self.label_43.setText(_translate("MainWindow", "STRAWBERRY SHAKE"))
        self.label_50.setText(_translate("MainWindow", "RS.50"))
        self.label_48.setText(_translate("MainWindow", "RS.50"))
        self.label_54.setText(_translate("MainWindow", "RS.40"))
        self.label_39.setText(_translate("MainWindow", "MINT MOJITO"))
        self.label_66.setText(_translate("MainWindow", "MOCHA CHOCOCHIP"))
        self.label_69.setText(_translate("MainWindow", "TROPICAL SUNDAE"))
        self.label_72.setText(_translate("MainWindow", "BROWN DEVIL SUNDAE"))
        self.label_73.setText(_translate("MainWindow", "RS.80"))
        self.label_75.setText(_translate("MainWindow", "<html><head/><body><p>CHOCOLATE CHIP MUFFIN</p></body></html>"))
        self.label_76.setText(_translate("MainWindow", "RS.40"))
        self.label_77.setText(_translate("MainWindow", "RS.70"))
        self.label_78.setText(_translate("MainWindow", "RS.80"))
        self.pushButton_9.setText(_translate("MainWindow", "BUY"))
        self.pushButton_10.setText(_translate("MainWindow", "PRINT BILL"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; color:#aa0000;\">CART</span></p></body></html>"))
        self.label_79.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#aa0000;\">BILL: </span></p></body></html>"))
        self.add.setText(_translate("MainWindow", "ADD"))
        self.remove.setText(_translate("MainWindow", "REMOVE"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; color:#aa0000;\">ITEM </span></p></body></html>"))
        self.label_70.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; color:#aa0000;\">QTY</span></p></body></html>"))
    def add_item(self):
        text=self.item.text().upper()
        text1=self.quantity.text().upper()
        length=len(text)
        length1 = len(text1)
        ans=self.order.check_validity(text)
        flag=0
        for i in text1:
            if i.isalpha():
                flag=1
        if (ans==0 or flag==1 or length==0 or length1==0):
            self.invalid = QtWidgets.QMessageBox()
            if ans==0 or length==0:
                self.invalid.setText("ITEM DOES NOT EXIST.  ")
            else:
                self.invalid.setText("ENTER CORRECT QUANTITY.  ")
            self.invalid.setWindowTitle("ERROR")
            self.invalid.setWindowIcon(QIcon('coffee.jpg'))
            self.invalid.show()
        else:
            self.order.cart(text, text1)
            self.display()

    def display(self):
        self.treeWidget.clear()
        self.treeWidget.setColumnCount(2)
        columns = ['ITEM', 'PRICE']
        self.treeWidget.setHeaderLabels(columns)
        table = self.order.get_cart()
        l = []
        for i in table:
            l.append(QtWidgets.QTreeWidgetItem(i))
        self.treeWidget.addTopLevelItems(l)

    def remove_item(self):
        text = self.item.text().upper()
        self.order.remove(text)
        self.display()
    def ok(self):
        bill=self.order.bill()
        self.database = Database.DatabaseUtility()
        available=self.database.check_cash(bill,self.cardno)
        if available==0:
            self.invalid1 = QtWidgets.QMessageBox()
            self.invalid1.setText("BALANCE IS LESS.   ")
            self.invalid1.setWindowTitle("ERROR")
            self.invalid1.setWindowIcon(QIcon('coffee.jpg'))
            self.invalid1.show()
        else:
            self.invalid1 = QtWidgets.QMessageBox()
            self.invalid1.setText("TRANSACTION SUCCESSFUL.   ")
            self.invalid1.setWindowTitle("ERROR")
            self.invalid1.setWindowIcon(QIcon('coffee.jpg'))
            self.invalid1.show()
            self.order.drop()
            self.order.disconnect()
        self.database.disconnect()
    def print_bill(self):
        bill_ammount=self.order.bill()
        bill_ammount="BILL :" + str(bill_ammount)
        self.label_79.setText(bill_ammount)
        self.label_79.setStyleSheet("font-size:24pt;color:#aa0000")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow,"CU1510991031")
    MainWindow.show()
    sys.exit(app.exec_())